CEP-559: Email template variable for generating identifiers
medullan/mautic pull request #18
Opened 2021-01-21 13:23 UTC by imanuelgittens

**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | No
| New feature? | Yes
| Automated tests included? | No
| Related user documentation PR URL | N/A
| Related developer documentation PR URL | N/A
| Issues addressed (#s or URLs) | N/A
| BC breaks? | None
| Deprecations? | None

[//]: # ( Required: )
#### Description: This PR allows for the use of a special token to generate a patient identifier

2021-01-22 14:58 UTC, zanchin requested changes

2021-01-22 14:58 UTC, zanchin commented on app/bundles/VARABundle/Helper/VARAHelper.php
> +        $id = uniqid();
Can we generate an ID with more entropy/characters? For example, using a uuid like https://symfony.com/blog/introducing-the-new-symfony-uuid-polyfill

2021-01-22 14:58 UTC, zanchin commented on app/bundles/LeadBundle/Helper/TokenHelper.php
> +            }
We should throw an error if there is no `varaid` contact field.

2021-03-20 19:35 UTC, zanchin commented on plugins/VARABundle/Helper/VARAClient.php
> +        $system = "http://vara.io/fhir/pro/recurring";
Can we make this just `http://vara.io/fhir/pro`?

2021-03-20 19:53 UTC, zanchin commented on plugins/VARABundle/Helper/VARAClient.php
> +      if (isset($multiple) && $multiple === TRUE) {
Multiple should default to TRUE because most resources for which we'll need to create identifiers support multiple values, sing single will be the exception. Only about 32 out of 102 resources (I checked) don't support multiple, but out of those only 3 (Consent, QuestionnaireResponse, ResearchSubject) are ones we'll likely care about.

2021-03-20 19:55 UTC, zanchin commented on plugins/VARABundle/Helper/VARAClient.php
> +      if (isset($multiple) && $multiple === TRUE) {
In fact, maybe we hard-code the single identifier list and don't require a parameter at all?

```
AdverseEvent
Bundle
ChargeItem
CodeSystem
Composition
ContentMap
Consent
contract
DetectedIssue
DeviceComponent
DeviceMetric
ExpansionProfile
GuidaneResponse
ImagingManifest
MeasureReport
MessageDefinition
QuestionnaireResponse
ResearchSubject
RiskAssessment
SupplyDelivery
SupplyRequest
TestReport
TestScript
```

2021-03-20 19:56 UTC, zanchin commented on plugins/VARABundle/Helper/VARAClient.php
> +    } catch (BadResponseException $ex) {
If a non-`BadResponseException` is thrown, will it continue up the stack?

2021-03-20 19:58 UTC, zanchin commented on plugins/VARABundle/Helper/VARAClient.php
> +      $response = $this->client->get("/fhir/3_0_1/$resource/$id");
Let's prep the update first (our new Identifier), and then make the GET call, update identifier, and then make the PUT call in tight succession. This way, we reduce the time spent between get/put (reducing the chance of a race condition), and keep all the HTTP/networking code separate from other code for error handling purposes.

2021-03-20 20:33 UTC, zanchin requested changes
See order of network operations and other comments

2021-03-25 14:59 UTC, keshavbahadoor commented on plugins/VARABundle/Helper/VARAClient.php
> +        $system = "http://vara.io/fhir/pro/recurring";
Updated.

2021-03-25 17:06 UTC, keshavbahadoor commented on plugins/VARABundle/Helper/VARAClient.php
> +      if (isset($multiple) && $multiple === TRUE) {
I'm going with the second approach as it eliminates the need for the multiple config parameter.  Less parameters for an engagement developer to worry about.

2021-03-31 15:03 UTC, keshavbahadoor commented on plugins/VARABundle/Helper/VARAClient.php
> +      $response = $this->client->get("/fhir/3_0_1/$resource/$id");
Addressed.

2021-04-13 03:04 UTC, zanchin approved these changes

2021-04-19 18:12 UTC, merged